<div class="alert alert-block alert-warning">
using <b style="color:blue"> Python </b> v3.10
<hr>
with <b> Jupyter Notebook </b> v7.5
</div>

<div class="alert alert-block alert-danger">
<!-- info, danger, warning, success -->
Import <b> Librraries</b>
</div>

In [19]:
import pandas as pd 
import numpy as np

In [20]:
dataset=pd.read_csv("Data_final.csv")
dataset   # to display the data

,O_score,C_score,E_score,A_score,N_score,Numerical Aptitude,Spatial Aptitude,Perceptual Aptitude,Abstract Reasoning,Verbal Reasoning,Career
0,5.45,8.67,3.45,5.34,4.23,9.23,4.56,6.78,7.89,6.12,Accountant
1,8.78,5.67,4.56,6.45,4.23,5.12,8.45,7.89,6.34,6.01,Graphic Designer
2,6.12,6.78,9.34,7.56,5.01,6.23,4.23,6.45,6.67,8.45,Salesperson
3,9.12,8.78,4.23,5.67,4.56,7.89,5.34,6.45,9.34,7.67,Research Scientist
4,6.45,7.56,5.67,9.12,4.23,5.34,4.01,6.23,5.78,8.67,Teacher
...,...,...,...,...,...,...,...,...,...,...,...
100,7.67,8.23,6.01,9.12,5.45,4.45,2.89,3.12,4.67,8.34,Foreign Service Officer
101,2.67,8.78,7.67,8.45,6.45,4.45,2.89,3.12,4.67,5.45,Customs and Border Protection Officer
102,6.78,8.67,4.23,5.23,4.67,8.23,7.67,6.01,7.45,5.45,Civil Engineer
103,7.34,7.67,4.23,5.23,4.67,9.34,8.45,6.78,8.12,5.67,Robotics Engineer
104,7.34,7.67,4.23,5.45,4.89,9.12,8.67,6.45,8.23,5.67,Electronics Design Engineer

# to display top rows

In [21]:
dataset.head(7)

,O_score,C_score,E_score,A_score,N_score,Numerical Aptitude,Spatial Aptitude,Perceptual Aptitude,Abstract Reasoning,Verbal Reasoning,Career
0,5.45,8.67,3.45,5.34,4.23,9.23,4.56,6.78,7.89,6.12,Accountant
1,8.78,5.67,4.56,6.45,4.23,5.12,8.45,7.89,6.34,6.01,Graphic Designer
2,6.12,6.78,9.34,7.56,5.01,6.23,4.23,6.45,6.67,8.45,Salesperson
3,9.12,8.78,4.23,5.67,4.56,7.89,5.34,6.45,9.34,7.67,Research Scientist
4,6.45,7.56,5.67,9.12,4.23,5.34,4.01,6.23,5.78,8.67,Teacher
5,8.45,7.01,5.34,5.45,4.56,6.45,9.12,7.67,8.89,4.23,Architect
6,4.01,8.23,6.67,9.34,5.12,4.56,4.45,7.45,5.78,7.78,Nurse

# to display bottom rows

In [22]:
dataset.tail()

,O_score,C_score,E_score,A_score,N_score,Numerical Aptitude,Spatial Aptitude,Perceptual Aptitude,Abstract Reasoning,Verbal Reasoning,Career
100,7.67,8.23,6.01,9.12,5.45,4.45,2.89,3.12,4.67,8.34,Foreign Service Officer
101,2.67,8.78,7.67,8.45,6.45,4.45,2.89,3.12,4.67,5.45,Customs and Border Protection Officer
102,6.78,8.67,4.23,5.23,4.67,8.23,7.67,6.01,7.45,5.45,Civil Engineer
103,7.34,7.67,4.23,5.23,4.67,9.34,8.45,6.78,8.12,5.67,Robotics Engineer
104,7.34,7.67,4.23,5.45,4.89,9.12,8.67,6.45,8.23,5.67,Electronics Design Engineer

# print number of rows and colum in dataset

In [23]:
print('rows: ', dataset.shape[0]) 
print('columns: ', dataset.shape[1])

rows:  105
columns:  11

# Print/Determine all the null columns in dataset:

In [24]:
dataset.isnull().sum()

O_score                0
C_score                0
E_score                0
A_score                0
N_score                0
Numerical Aptitude     0
Spatial Aptitude       0
Perceptual Aptitude    0
Abstract Reasoning     0
Verbal Reasoning       0
Career                 0
dtype: int64

# Filling null values using mean / median / mode:

In [25]:
dataset = dataset.fillna(dataset.mean)

In [26]:
dataset = dataset.fillna(dataset.median)

In [27]:
dataset = dataset.fillna(dataset.mode)

# Print datatype of each column:

In [28]:
dataset.dtypes

O_score                float64
C_score                float64
E_score                float64
A_score                float64
N_score                float64
Numerical Aptitude     float64
Spatial Aptitude       float64
Perceptual Aptitude    float64
Abstract Reasoning     float64
Verbal Reasoning       float64
Career                  object
dtype: object

# show colums which have numerical values

In [29]:
dataset.describe()

,O_score,C_score,E_score,A_score,N_score,Numerical Aptitude,Spatial Aptitude,Perceptual Aptitude,Abstract Reasoning,Verbal Reasoning
count,105.000000,105.000000,105.000000,105.000000,105.000000,105.000000,105.000000,105.000000,105.000000,105.000000
mean,7.294857,7.538286,5.548952,6.863714,5.466381,5.939619,4.376476,5.163810,5.724190,6.794381
std,1.398485,1.215005,1.643137,1.515778,0.868926,1.958362,1.948409,1.747213,1.872927,1.495273
min,2.670000,3.560000,2.890000,3.230000,2.890000,2.890000,2.340000,3.010000,3.010000,3.450000
25%,6.670000,7.340000,4.230000,5.450000,4.670000,4.450000,3.120000,3.670000,4.340000,5.450000
50%,7.230000,7.670000,5.230000,6.450000,5.450000,5.120000,3.450000,4.450000,4.670000,7.450000
75%,8.670000,8.340000,7.010000,8.120000,6.010000,7.780000,4.450000,6.780000,7.670000,8.120000
max,9.450000,9.450000,9.340000,9.340000,8.120000,9.450000,9.230000,9.340000,9.340000,9.340000

# Number of repeated values

In [30]:
dataset.nunique()

O_score                 32
C_score                 29
E_score                 31
A_score                 31
N_score                 23
Numerical Aptitude      35
Spatial Aptitude        28
Perceptual Aptitude     28
Abstract Reasoning      36
Verbal Reasoning        31
Career                 104
dtype: int64

# to show colums

In [31]:
dataset.count()

O_score                105
C_score                105
E_score                105
A_score                105
N_score                105
Numerical Aptitude     105
Spatial Aptitude       105
Perceptual Aptitude    105
Abstract Reasoning     105
Verbal Reasoning       105
Career                 105
dtype: int64

# Printing rows and colums / shape of dataframe

In [32]:
print('We have {} rows.'.format(dataset.shape[0])) 
print('We have {} columns'.format(dataset.shape[1]))

We have 105 rows.
We have 11 columns

# checking all null values

In [33]:
np.sum(pd.isnull(dataset))

C:\Users\HP\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\numpy\_core\fromnumeric.py:84: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)

O_score                0
C_score                0
E_score                0
A_score                0
N_score                0
Numerical Aptitude     0
Spatial Aptitude       0
Perceptual Aptitude    0
Abstract Reasoning     0
Verbal Reasoning       0
Career                 0
dtype: int64

#  Checking unique values of specific column

In [38]:
dataset['Career'].unique()

array(['Accountant', 'Graphic Designer', 'Salesperson',
       'Research Scientist', 'Teacher', 'Architect', 'Nurse',
       'Software Developer', 'Psychologist', 'Chef', 'Marketing Manager',
       'Physician', 'Artist', 'Human Resources Manager',
       'Construction Engineer', 'Journalist', 'Astronomer',
       'Financial Analyst', 'Biologist', 'Event Planner',
       'Real Estate Agent', 'Environmental Scientist', 'Lawyer',
       'IT Support Specialist', 'Fashion Designer',
       'Marketing Coordinator', 'Biomedical Engineer',
       'Event Photographer', 'Data Analyst', 'Pharmacist',
       'Social Worker', 'Financial Planner', 'Biotechnologist',
       'HR Recruiter', 'Software Quality Assurance Tester',
       'Elementary School Teacher', 'Industrial Engineer',
       'Market Research Analyst', 'Financial Auditor', 'Musician',
       'Police Detective', 'Marketing Copywriter', 'Zoologist',
       'Speech Therapist', 'Mechanical Engineer', 'Forensic Scientist',
       'Social Media Manager', 'Geologist', 'Web Developer',
       'Wildlife Biologist', 'Air Traffic Controller', 'Game Developer',
       'Urban Planner', 'Financial Advisor', 'Airline Pilot',
       'Environmental Engineer', 'Interior Designer',
       'Physical Therapist', 'Mechanical Designer', 'Dental Hygienist',
       'Marketing Analyst', 'Aerospace Engineer', 'Pediatric Nurse',
       'Advertising Executive', 'Wildlife Conservationist',
       'IT Project Manager', 'Forestry Technician', 'Video Game Tester',
       'Marriage Counselor', 'Biomedical Researcher',
       'Database Administrator', 'Public Relations Specialist',
       'Genetic Counselor', 'Market Researcher', 'Occupational Therapist',
       'Electrical Engineer', 'Investment Banker', 'Marine Biologist',
       'Human Rights Lawyer', 'Database Analyst', 'Pediatrician',
       'Technical Writer', 'Forensic Psychologist', 'Product Manager',
       'Fashion Stylist', 'Speech Pathologist', 'Public Health Analyst',
       'Sports Coach', 'Insurance Underwriter', 'Chiropractor',
       'Radiologic Technologist', 'Tax Accountant',
       'Quality Control Inspector', 'Rehabilitation Counselor',
       'Film Director', 'Diplomat', 'Police Officer',
       'Administrative Officer', 'Tax Collector',
       'Foreign Service Officer', 'Customs and Border Protection Officer',
       'Civil Engineer', 'Robotics Engineer',
       'Electronics Design Engineer'], dtype=object)